# This file is created by Ye Ding
# Does the al-Folio them work? not, got email of fail notice, it was on their list
#theme: Al-Folio
# add theme instruction: https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/adding-a-theme-to-your-github-pages-site-using-jekyll#adding-a-theme
# theme: minima
# adding Al-Folio as remote theme works
#remote_theme: Al-Folio
theme: minima 
title: Sfold
description: Sfold static
